// <auto-generated />
using System;
using ArtGallery;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArtGallery.Migrations
{
    [DbContext(typeof(GalleryDbContext))]
    [Migration("20240606214414_added_periods_table")]
    partial class added_periods_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArtGallery.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdminId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AdminId");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("ArtGallery.Models.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArtistId"));

                    b.Property<string>("Biography")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Movement")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Profession")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ArtistId");

                    b.ToTable("Artists", (string)null);
                });

            modelBuilder.Entity("ArtGallery.Models.Artwork", b =>
                {
                    b.Property<int>("ArtworkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArtworkId"));

                    b.Property<int?>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<string>("History")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MuseumId")
                        .HasColumnType("integer");

                    b.Property<int?>("PeriodId")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("ArtworkId");

                    b.HasIndex("ArtistId");

                    b.HasIndex("MuseumId");

                    b.HasIndex("PeriodId");

                    b.ToTable("Artworks", (string)null);
                });

            modelBuilder.Entity("ArtGallery.Models.Museum", b =>
                {
                    b.Property<int>("MuseumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MuseumId"));

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Inauguration")
                        .HasColumnType("integer");

                    b.Property<float?>("Latitude")
                        .HasColumnType("real");

                    b.Property<float?>("Longitude")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.HasKey("MuseumId");

                    b.ToTable("Museums", (string)null);
                });

            modelBuilder.Entity("ArtGallery.Models.Period", b =>
                {
                    b.Property<int>("PeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PeriodId"));

                    b.Property<int>("End")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Start")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PeriodId");

                    b.ToTable("Periods", (string)null);

                    b.HasData(
                        new
                        {
                            PeriodId = 1,
                            End = -3000,
                            Name = "Prehistoric Art",
                            Start = -40000,
                            Summary = "Art from the prehistoric era, characterized by cave paintings, carvings, and megalithic structures."
                        },
                        new
                        {
                            PeriodId = 2,
                            End = -332,
                            Name = "Ancient Egyptian Art",
                            Start = -3000,
                            Summary = "Art from ancient Egypt, known for its monumental structures, hieroglyphics, and stylized depictions of figures."
                        },
                        new
                        {
                            PeriodId = 3,
                            End = -146,
                            Name = "Ancient Greek Art",
                            Start = -800,
                            Summary = "Art from ancient Greece, renowned for its sculptures, pottery, and architectural achievements like the Parthenon."
                        },
                        new
                        {
                            PeriodId = 4,
                            End = 476,
                            Name = "Ancient Roman Art",
                            Start = -146,
                            Summary = "Art from ancient Rome, noted for its engineering, architecture, and realistic sculptures."
                        },
                        new
                        {
                            PeriodId = 5,
                            End = 1453,
                            Name = "Byzantine Art",
                            Start = 330,
                            Summary = "Art from the Byzantine Empire, characterized by religious mosaics, icons, and architecture."
                        },
                        new
                        {
                            PeriodId = 6,
                            End = 1400,
                            Name = "Medieval Art",
                            Start = 500,
                            Summary = "Art from the Middle Ages, including Romanesque and Gothic art, notable for its religious themes and manuscript illuminations."
                        },
                        new
                        {
                            PeriodId = 7,
                            End = 1600,
                            Name = "Renaissance Art",
                            Start = 1400,
                            Summary = "Art from the Renaissance period, marked by a revival of classical learning and wisdom, and an emphasis on humanism."
                        },
                        new
                        {
                            PeriodId = 8,
                            End = 1750,
                            Name = "Baroque Art",
                            Start = 1600,
                            Summary = "Art from the Baroque period, known for its exuberance, grandeur, and dramatic use of light and shadow."
                        },
                        new
                        {
                            PeriodId = 9,
                            End = 1770,
                            Name = "Rococo Art",
                            Start = 1700,
                            Summary = "Art from the Rococo period, characterized by its ornate and decorative style, often with themes of love and nature."
                        },
                        new
                        {
                            PeriodId = 10,
                            End = 1830,
                            Name = "Neoclassicism",
                            Start = 1760,
                            Summary = "Art from the Neoclassical period, inspired by the classical art and culture of ancient Greece and Rome."
                        },
                        new
                        {
                            PeriodId = 11,
                            End = 1850,
                            Name = "Romanticism",
                            Start = 1800,
                            Summary = "Art from the Romantic period, emphasizing emotion, individualism, and nature."
                        },
                        new
                        {
                            PeriodId = 12,
                            End = 1900,
                            Name = "Realism",
                            Start = 1848,
                            Summary = "Art from the Realist period, focused on depicting everyday subjects and scenes in a naturalistic manner."
                        },
                        new
                        {
                            PeriodId = 13,
                            End = 1890,
                            Name = "Impressionism",
                            Start = 1860,
                            Summary = "Art from the Impressionist period, characterized by small, thin brush strokes, open composition, and emphasis on light and its changing qualities."
                        },
                        new
                        {
                            PeriodId = 14,
                            End = 1905,
                            Name = "Post-Impressionism",
                            Start = 1886,
                            Summary = "Art from the Post-Impressionist period, which extended Impressionism while rejecting its limitations, emphasizing more abstract qualities."
                        },
                        new
                        {
                            PeriodId = 15,
                            End = 1910,
                            Name = "Fauvism",
                            Start = 1905,
                            Summary = "Art from the Fauvist period, known for its bold, vibrant colors and simplified forms."
                        },
                        new
                        {
                            PeriodId = 16,
                            End = 1920,
                            Name = "Expressionism",
                            Start = 1905,
                            Summary = "Art from the Expressionist period, aiming to depict the emotional experience rather than physical reality."
                        },
                        new
                        {
                            PeriodId = 17,
                            End = 1922,
                            Name = "Cubism",
                            Start = 1907,
                            Summary = "Art from the Cubist period, characterized by fragmented and abstracted forms, and multiple perspectives within a single composition."
                        },
                        new
                        {
                            PeriodId = 18,
                            End = 1944,
                            Name = "Futurism",
                            Start = 1909,
                            Summary = "Art from the Futurist period, focused on themes of modernity, technology, and movement."
                        },
                        new
                        {
                            PeriodId = 19,
                            End = 1923,
                            Name = "Dada",
                            Start = 1916,
                            Summary = "Art from the Dada movement, known for its avant-garde and anti-art stance, often employing absurdity and satire."
                        },
                        new
                        {
                            PeriodId = 20,
                            End = 1966,
                            Name = "Surrealism",
                            Start = 1924,
                            Summary = "Art from the Surrealist period, aimed at expressing the unconscious mind through dream-like and fantastical imagery."
                        },
                        new
                        {
                            PeriodId = 21,
                            End = 1965,
                            Name = "Abstract Expressionism",
                            Start = 1943,
                            Summary = "Art from the Abstract Expressionist period, characterized by large-scale, abstract paintings that emphasize spontaneous, automatic, or subconscious creation."
                        },
                        new
                        {
                            PeriodId = 22,
                            End = 1970,
                            Name = "Pop Art",
                            Start = 1950,
                            Summary = "Art from the Pop Art movement, which draws inspiration from popular and commercial culture, often using irony and parody."
                        },
                        new
                        {
                            PeriodId = 23,
                            End = 1975,
                            Name = "Minimalism",
                            Start = 1960,
                            Summary = "Art from the Minimalist period, known for its simplicity, use of geometric shapes, and reduction to essential forms."
                        },
                        new
                        {
                            PeriodId = 24,
                            End = 2024,
                            Name = "Contemporary Art",
                            Start = 1970,
                            Summary = "Art from the Contemporary period, encompassing a diverse range of styles, techniques, and themes from the late 20th century to the present."
                        });
                });

            modelBuilder.Entity("ArtGallery.Models.Artwork", b =>
                {
                    b.HasOne("ArtGallery.Models.Artist", "Artist")
                        .WithMany("Artworks")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ArtGallery.Models.Museum", "Museum")
                        .WithMany("Artworks")
                        .HasForeignKey("MuseumId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ArtGallery.Models.Period", "Period")
                        .WithMany("Artworks")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Artist");

                    b.Navigation("Museum");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("ArtGallery.Models.Artist", b =>
                {
                    b.Navigation("Artworks");
                });

            modelBuilder.Entity("ArtGallery.Models.Museum", b =>
                {
                    b.Navigation("Artworks");
                });

            modelBuilder.Entity("ArtGallery.Models.Period", b =>
                {
                    b.Navigation("Artworks");
                });
#pragma warning restore 612, 618
        }
    }
}
